# Configuração do GitHub Pages
title: "Tarifa Zero Cuiabá"
description: "Movimento pela implementação da Tarifa Zero no transporte público de Cuiabá"
baseurl: "/Cuiaba-busao-gratis/"
url: "https://github.com/Posso-Mais.github.io"

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO settings
lang: pt-BR
author: "Movimento Tarifa Zero Cuiabá"

# Social media
social:
  facebook: "#"
  instagram: "#"
  twitter: "#"
  whatsapp: "#"

# Google Analytics (opcional)
google_analytics: "G-JTBNX420HN"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
